{{- if .Values.kibana.ingress.enabled -}}
{{- $fullName := include "fullname.kibana" . -}}
{{- $ingressPath := .Values.kibana.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "name.kibana" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.kibana.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.kibana.ingress.hosts  }}
      http:
        paths:
        - path: {{ .Values.kibana.ingress.path }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullName }}
              port: 
                number: 5601

{{- end }}
